In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt 
import h5py as h5

W01 = 30
W12 = 150
W23 = 75
W34 = 40
W45 = 20
W56 = 3

# Take in params
# Read H5 file
f = h5.File("MLPmodel_1hand_float32.h5", "r")
# Get and print list of datasets within the H5 file
datasetNames = list(f.keys())

# for k1 in f:
#     print(k1)
#     for k2 in f[k1].keys():
#         print(k2)
#         for k3 in f[k1][k2].keys():  
#             print(k3)

b1 = f['dense_50']['dense_50']['bias:0'].value
b2 = f['dense_51']['dense_51']['bias:0'].value
b3 = f['dense_52']['dense_52']['bias:0'].value
b4 = f['dense_53']['dense_53']['bias:0'].value
b5 = f['dense_54']['dense_54']['bias:0'].value
w1 = f['dense_50']['dense_50']['kernel:0'].value
w2 = f['dense_51']['dense_51']['kernel:0'].value
w3 = f['dense_52']['dense_52']['kernel:0'].value
w4 = f['dense_53']['dense_53']['kernel:0'].value
w5 = f['dense_54']['dense_54']['kernel:0'].value
print(w5)

/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


[[ 0.08123934  0.22633007 -0.45906982]
 [-0.4003266  -0.39515147  0.19738607]
 [ 0.02016203 -0.51434934 -0.07237569]
 [ 0.41343328  0.5591861   0.08986615]
 [ 0.0372792  -0.00734939  0.38781783]
 [-0.22866112  0.34458584  0.4349286 ]
 [-0.22231954 -0.6384507  -0.37000492]
 [ 0.37414655  0.0835006  -0.5715021 ]
 [-0.23362124 -0.18657465 -0.05473055]
 [-0.07523619  0.06759576 -0.26091665]
 [ 0.40718314 -0.59276384  0.52903426]
 [ 0.39106014  0.2865478  -0.01253801]
 [ 0.41452312  0.11144286  0.24612206]
 [-0.3654425   0.37177154 -0.26599732]
 [ 0.5756203   0.02611143  0.4850059 ]
 [ 0.42094326 -0.5292319  -0.41618565]
 [-0.23864685 -0.34981027 -0.42076483]
 [-0.01724146  0.58110344 -0.3847386 ]
 [-0.4629779   0.06747911 -0.33100867]
 [ 0.40318015  0.3454814   0.3426991 ]]


In [2]:
# b1 = np.zeros((1,W12), dtype='f4')
# w1 = np.zeros((W01,W12), dtype='f4')
# b2 = np.zeros((1,W23), dtype='f4')
# w2 = np.zeros((W12,W23), dtype='f4')
# b3 = np.zeros((1,W34), dtype='f4')
# w3 = np.zeros((W23,W34), dtype='f4')
# b4 = np.zeros((1,W45), dtype='f4')
# w4 = np.zeros((W34,W45), dtype='f4')
# b5 = np.zeros((1,W56), dtype='f4')
# w5 = np.zeros((W45,W56), dtype='f4')


# len(weights)

# for i in range(W12):
#     b1[0][i] = weights[i]
# for i in range(W01):
#     for j in range(W12):
#         w1[i][j] = weights[i*W01+j+W12]

# prev_sum = W12+W01*W12
# for i in range(W23):
#     b2[0][i] = weights[i+prev_sum]
    
# for i in range(W12):
#     for j in range(W23):
# #         print(i*W12+j+prev_sum+W23)
#         w2[i][j] = weights[i*W23+j+prev_sum+W23]

# prev_sum += W23+W12*W23
# for i in range(W34):
#     b3[0][i] = weights[i+prev_sum]
# for i in range(W23):
#     for j in range(W34):
#         w3[i][j] = weights[i*W34+j+prev_sum+W34]

# prev_sum += W34+W23*W34
# for i in range(W45):
#     b4[0][i] = weights[i+prev_sum]
# for i in range(W34):
#     for j in range(W45):
#         w4[i][j] = weights[i*W45+j+prev_sum+W45]
        
# prev_sum += W45+W34*W45
# for i in range(W56):
#     b5[0][i] = weights[i+prev_sum]
# for i in range(W45):
#     for j in range(W56):
#         w5[i][j] = weights[i*W56+j+prev_sum+W56]
           
# print(b1)

In [4]:
motion_data_directory = "Logs for week 11"

from os import listdir
from os.path import isfile, join
file_path = './' + motion_data_directory
all_files = [f for f in listdir(file_path) if isfile(join(file_path, f))]

def obtain_side_and_action_df(side, dance):
  df = pd.read_csv('./trial2/' + dance + '/' + side + '.csv')
  temp = []
  for i in df.columns:
    temp.append(side + '_' + i)
  df.columns = temp
  return df

def join_df(left, right):
  return pd.concat([left, right], axis=1)

def get_joined_df(move):
  temp_df_list = []
  for file in all_files:
    if move in file:
      temp_df = pd.read_csv(file_path + '/' + file)
      temp_df_list.append(temp_df)
  
  df = pd.concat(temp_df_list)
  return df

side_pump = get_joined_df('Sidepump')
hair = get_joined_df('Hair')
gun = get_joined_df('Gun')

movement_list = [side_pump, hair, gun]
# movement_list = [downstairs_df_list]
action_reference = [1,2,3]
movement = ["side_pump", "hair", "gun"]

df_combined = pd.DataFrame(columns=[ 
       'accel.x', 'accel.y',
       'accel.z', 'gyro.x', 'gyro.y', 'gyro.z',
       'action'])

for i in range(len(movement_list)):
  action = movement_list[i]
  action['action'] = movement[i]
  frames = [df_combined, action]
  df_combined = pd.concat(frames)

df_temp = pd.DataFrame()
df_temp["action"] = df_combined['action']
df_combined = df_combined.drop(['action'], axis=1)
df_combined = df_combined.drop(['timestamp'], axis=1)
df_combined['action'] = df_temp['action']
df_combined

accel.x   accel.y   accel.z    gyro.x    gyro.y    gyro.z     action
0    0.103884 -0.074545  0.376018  0.007634 -0.015267  0.000000  side_pump
1    0.116458 -0.097298  0.379012  0.015267  0.000000 -0.015267  side_pump
2    0.084125 -0.069755  0.407453  0.015267  0.000000  0.000000  side_pump
3    0.104183 -0.054187  0.363444 -0.007634  0.015267 -0.007634  side_pump
4    0.091310 -0.115260  0.336500  0.068702  0.015267  0.038168  side_pump
5    0.068857 -0.114961  0.337698 -0.007634  0.068702 -0.053435  side_pump
6    0.119452 -0.114362  0.390987  0.038168 -0.015267 -0.030534  side_pump
7    0.174537 -0.220342  0.192200  0.083969 -0.038168 -0.030534  side_pump
8    0.170645 -0.159269  0.209564 -0.053435  0.038168 -0.030534  side_pump
9    0.119452 -0.125439  0.326321 -0.030534  0.015267  0.015267  side_pump
10   0.125739 -0.149988  0.275727  0.007634  0.007634  0.030534  side_pump
11   0.059576 -0.122146  0.280816 -0.015267 -0.015267  0.015267  side_pump
12  -0.559237  0.683179  1.430425 -0.366412 -0.068702  0.267176  side_pump
13   0.217348  0.963696  1.061293 -0.946565 -0.007634 -0.297710  side_pump
14   3.000959  4.566404 -0.858016 -0.633588  0.412214  0.312977  side_pump
15  -2.640210  5.842051 -1.637295 -0.671756  1.244275  2.259542  side_pump
16  -0.443378 -1.162782  0.771196 -0.786260  0.068702  1.106870  side_pump
17   2.686613 -0.442180  0.952320 -0.152672 -0.755725 -0.175573  side_pump
18   1.343905  1.153801  1.829795 -0.251908 -0.343511 -1.587786  side_pump
19   0.522114  1.431623 -1.249003 -0.572519 -0.068702 -2.458015  side_pump
20   0.922981  4.407135 -2.179168 -0.167939  0.854962  0.267176  side_pump
21  -3.813170  2.493215  0.944236 -0.969466  1.083969  2.236641  side_pump
22  -0.290097 -1.596879  0.588576 -0.648855 -0.091603  0.793893  side_pump
23   2.208807  0.222138 -0.123344 -0.503817 -0.503817 -0.648855  side_pump
24   1.121468  1.472039  1.657653 -0.190840 -0.335878 -0.755725  side_pump
25   1.129850  0.938548  1.583108 -0.274809 -0.045802 -0.526718  side_pump
26   0.743354  0.672102  1.694177  0.122137 -0.221374 -0.152672  side_pump
27   0.528102  0.813708  2.228266 -0.053435 -0.091603  0.312977  side_pump
28   0.776585  0.339793  2.374961  0.106870  0.000000  0.061069  side_pump
29   0.815205  0.723595  2.398911 -0.022901  0.007634 -0.198473  side_pump
..        ...       ...       ...       ...       ...       ...        ...
680  1.455573 -1.627416  0.531395 -0.603053  0.206107 -1.648855        gun
681 -1.290616 -0.320933  0.988544  0.519084  0.099237 -2.564885        gun
682 -2.817740  0.331411  0.156874  0.442748  0.160305 -3.305344        gun
683  0.956511 -1.634900  0.045805 -1.923664 -0.038168  0.068702        gun
684  1.161884 -1.150807  0.195793  0.290076  0.122137 -0.022901        gun
685  1.128054 -0.917292  0.276625 -0.175573 -0.045802  0.030534        gun
686  1.015488 -1.019979  0.270038 -0.083969 -0.022901  0.015267        gun
687  0.927172 -0.745150  0.243693  0.091603 -0.007634 -0.007634        gun
688  0.852328 -0.636177  0.146695 -0.045802  0.007634  0.030534        gun
689  0.824186 -0.679587  0.138911 -0.053435  0.007634  0.022901        gun
690  0.760119 -0.604443  0.126038  0.015267  0.000000 -0.007634        gun
691  0.686472 -0.494572  0.096998 -0.007634  0.007634  0.000000        gun
692  0.638572 -0.458347  0.063169 -0.022901  0.000000  0.000000        gun
693  0.592169 -0.408650  0.048200  0.000000  0.000000 -0.007634        gun
694  0.537682 -0.342488  0.014969  0.000000  0.007634  0.007634        gun
695  0.506247 -0.323328  0.007185 -0.007634  0.000000  0.000000        gun
696  0.443977 -0.265548  0.000000 -0.022901  0.000000  0.000000        gun
697  0.409548 -0.252974 -0.000299  0.007634 -0.007634  0.000000        gun
698  0.338596 -0.228724 -0.034428  0.061069  0.000000 -0.015267        gun
699  0.321831 -0.218246 -0.066761 -0.015267  0.007634  0.007634        gun
700  0.304167 -0.232317 -0.049098 -0.022901  0.000000  0.000000        gun
701  0.278720 -0.179028 -0.0487

In [5]:
df_combined = df_combined.reset_index()
df_combined = df_combined.drop(columns=['index'])
df_combined
from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()
df_combined['action_label'] = label.fit_transform(df_combined['action'])
label.classes_

array(['gun', 'hair', 'side_pump'], dtype=object)

In [6]:
col_names = []
for col_name in df_combined.columns:
  col_names.append(col_name)

X = df_combined[col_names[0:6]]
y = df_combined['action_label']

from sklearn.preprocessing import  StandardScaler

scaler = StandardScaler()

X = scaler.fit_transform(X)
scaled_X = pd.DataFrame(data = X, columns = col_names[0:6])
scaled_X['action_label'] = y.values

In [7]:
import scipy.stats as stats

data_frequency = 10 #50hz
frame_size = data_frequency * 6
sliding = data_frequency * 3

def get_frames(df, frame_size, sliding):
  num_features = 6

  frames = []
  labels = []
  for i in range(0, len(df) - frame_size, sliding):
    accel_x = df['accel.x'].values[i:i+frame_size]
    accel_y = df['accel.y'].values[i:i+frame_size]
    accel_z = df['accel.z'].values[i:i+frame_size]
    gyro_x = df['gyro.x'].values[i:i+frame_size]
    gyro_y = df['gyro.y'].values[i:i+frame_size]
    gyro_z = df['gyro.z'].values[i:i+frame_size]

    label = stats.mode(df['action_label'][i:i+frame_size])[0][0]
    frames.append([accel_x,accel_y,accel_z,gyro_x,gyro_y,gyro_z])
    labels.append(label)
  
  frames = np.asarray(frames).reshape(-1, frame_size, num_features)
  labels = np.asarray(labels)
  return frames, labels

In [8]:
X, y = get_frames(scaled_X, frame_size, sliding)

In [11]:
# from scipy.stats import iqr
# from scipy.stats import skew

# # Extracted features:
# # Mean acceleration & rotation
# mean_uAx = []
# mean_uAy = []
# mean_uAz = []
# mean_uRx = []
# mean_uRy = []
# mean_uRz = []

# # S.d. acceleration & rotation
# sd_uAx = []
# sd_uAy = []
# sd_uAz = []
# sd_uRx = []
# sd_uRy = []
# sd_uRz = []

# # iqr acceleration & rotation
# iqr_uAx = []
# iqr_uAy = []
# iqr_uAz = []
# iqr_uRx = []
# iqr_uRy = []
# iqr_uRz = []

# # skewness
# skew_uAx = []
# skew_uAy = []
# skew_uAz = []
# skew_uRx = []
# skew_uRy = []
# skew_uRz = []

# # minimum
# min_uAx = []
# min_uAy = []
# min_uAz = []
# min_uRx = []
# min_uRy = []
# min_uRz = []

# # Maximum
# max_uAx = []
# max_uAy = []
# max_uAz = []
# max_uRx = []
# max_uRy = []
# max_uRz = []

# #Energy
# energy_uAx = []
# energy_uAy = []
# energy_uAz = []
# energy_uRx = []
# energy_uRy = []
# energy_uRz = []

# def calculate_energy(accel):
#   delta_time = 2 #2 second window
#   velocity = integrate.quad(lambda x: accel, 0, delta_time)
#   energy = 0.5 * 75 * (velocity**2)
#   return energy

# for i in range(len(X)):
#   mean_uAx.append(np.mean(X[i], axis=0)[0])
#   mean_uAy.append(np.mean(X[i], axis=0)[1])
#   mean_uAz.append(np.mean(X[i], axis=0)[2])
#   mean_uRx.append(np.mean(X[i], axis=0)[3])
#   mean_uRy.append(np.mean(X[i], axis=0)[4])
#   mean_uRz.append(np.mean(X[i], axis=0)[5])

#   sd_uAx.append(np.std(X[i], axis=0)[0])
#   sd_uAy.append(np.std(X[i], axis=0)[1])
#   sd_uAz.append(np.std(X[i], axis=0)[2])
#   sd_uRx.append(np.std(X[i], axis=0)[3])
#   sd_uRy.append(np.std(X[i], axis=0)[4])
#   sd_uRz.append(np.std(X[i], axis=0)[5])
  
#   iqr_uAx.append(iqr(X[i], axis=0)[0])
#   iqr_uAy.append(iqr(X[i], axis=0)[1])
#   iqr_uAz.append(iqr(X[i], axis=0)[2])
#   iqr_uRx.append(iqr(X[i], axis=0)[3])
#   iqr_uRy.append(iqr(X[i], axis=0)[4])
#   iqr_uRz.append(iqr(X[i], axis=0)[5])

#   skew_uAx.append(skew(X[i], axis=0)[0])
#   skew_uAy.append(skew(X[i], axis=0)[1])
#   skew_uAz.append(skew(X[i], axis=0)[2])
#   skew_uRx.append(skew(X[i], axis=0)[3])
#   skew_uRy.append(skew(X[i], axis=0)[4])
#   skew_uRz.append(skew(X[i], axis=0)[5])

#   min_uAx.append(X[i].min(axis=0)[0])
#   min_uAy.append(X[i].min(axis=0)[1])
#   min_uAz.append(X[i].min(axis=0)[2])
#   min_uRx.append(X[i].min(axis=0)[3])
#   min_uRy.append(X[i].min(axis=0)[4])
#   min_uRz.append(X[i].min(axis=0)[5])

#   max_uAx.append(X[i].max(axis=0)[0])
#   max_uAy.append(X[i].max(axis=0)[1])
#   max_uAz.append(X[i].max(axis=0)[2])
#   max_uRx.append(X[i].max(axis=0)[3])
#   max_uRy.append(X[i].max(axis=0)[4])
#   max_uRz.append(X[i].max(axis=0)[5])

# # Create 2D Matrix for Decision Tree
# feature_extracted_data = pd.DataFrame(
#     {'mean_uAx': mean_uAx,
#      'mean_uAy': mean_uAy,
#      'mean_uAz': mean_uAz,
#      'mean_uRx': mean_uRx,
#      'mean_uRy': mean_uRy,
#      'mean_uRz': mean_uRz,
#      'sd_uAx': sd_uAx,
#      'sd_uAy': sd_uAy,
#      'sd_uAz': sd_uAz,
#      'sd_uRx': sd_uRx,
#      'sd_uRy': sd_uRy,
#      'sd_uRz': sd_uRz,
#      'iqr_uAx': iqr_uAx,
#      'iqr_uAy': iqr_uAy,
#      'iqr_uAz': iqr_uAz,
#      'iqr_uRx': iqr_uRx,
#      'iqr_uRy': iqr_uRy,
#      'iqr_uRz': iqr_uRz,
#     #  'skew_uAx': skew_uAx,
#     #  'skew_uAy': skew_uAy,
#     #  'skew_uAz': skew_uAz,
#     #  'skew_uRx': skew_uRx,
#     #  'skew_uRy': skew_uRy,
#     #  'skew_uRz': skew_uRz,
#      'min_uAx': min_uAx,
#      'min_uAy': min_uAy,
#      'min_uAz': min_uAz,
#      'min_uRx': min_uRx,
#      'min_uRy': min_uRy,
#      'min_uRz': min_uRz,
#      'max_uAx': max_uAx,
#      'max_uAy': max_uAy,
#      'max_uAz': max_uAz,
#      'max_uRx': max_uRx,
#      'max_uRy': max_uRy,
#      'max_uRz': max_uRz,
#     })

# mat = feature_extracted_data.copy()
# reorder = pd.DataFrame()
# col_list = ['mean_uAx',
#      'mean_uAy',
#      'mean_uAz',
#      'mean_uRx',
#      'mean_uRy',
#      'mean_uRz',
#      'sd_uAx',
#      'sd_uAy',
#      'sd_uAz',
#      'sd_uRx',
#      'sd_uRy',
#      'sd_uRz',
#      'iqr_uAx',
#      'iqr_uAy',
#      'iqr_uAz',
#      'iqr_uRx',
#      'iqr_uRy',
#      'iqr_uRz',
#      'min_uAx',
#      'min_uAy',
#      'min_uAz',
#      'min_uRx',
#      'min_uRy',
#      'min_uRz',
#      'max_uAx',
#      'max_uAy',
#      'max_uAz',
#      'max_uRx',
#      'max_uRy',
#      'max_uRz']
# for col_name in col_list:
#     reorder[col_name] = mat[col_name]
# mat = reorder.copy()
# mat

mat = pd.read_csv('matrix.csv')
mat = mat.drop(['Unnamed: 0'], axis=1)
mat.head()

mean_uAx  mean_uAy  mean_uAz  mean_uRx  mean_uRy  mean_uRz    sd_uAx  \
0 -0.191310 -0.091345 -0.054093 -0.107405 -0.119382 -0.098222  0.936158   
1 -0.082301  0.022723  0.066186  0.139453  0.157301  0.082761  1.059264   
2 -0.061715  0.011121  0.065387  0.238968  0.288613  0.157998  0.887878   
3  0.068977  0.002638  0.001101  0.119204  0.224209  0.165819  0.915486   
4  0.119860  0.115296  0.065837  0.004679  0.009521  0.052093  1.021557   

     sd_uAy    sd_uAz    sd_uRx    ...      min_uAz   min_uRx   min_uRy  \
0  0.932833  1.171113  0.984434    ...     0.020499 -0.834377 -0.961301   
1  1.015244  1.191559  1.082712    ...     0.410869 -0.221766 -2.572426   
2  0.782266  0.934637  1.042773    ...     0.274678  0.073784 -1.602706   
3  0.866669  0.992671  1.033227    ...    -0.133068  0.367844 -1.534197   
4  0.998832  0.986937  0.969667    ...     1.377444  0.181346 -1.545615   

    min_uRz   max_uAx   max_uAy   max_uAz   max_uRx   max_uRy   max_uRz  
0 -1.677504 -0.036096  0.022153  0.121277  0.017851  0.916083  1.757058  
1 -1.741876  1.757058  0.602496  0.505689  1.363875  2.084380  2.650822  
2 -1.154583  2.650822  0.807362  0.467960  0.570227  1.422124  2.165135  
3 -1.746840  2.165135  0.875871  0.495926  0.523396  1.803227  1.948023  
4 -1.416871  1.948023  0.679941  1.377444  0.300162  1.442313  2.246220  

[5 rows x 30 columns]

In [12]:
y = np.array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(mat, y, test_size=0.9, random_state = 0, stratify = y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape
type(X_test.values[1][2])

numpy.float64

In [14]:
def relu(X):
    return np.maximum(0,X)

def softmax(X):
    expo = np.exp(X)
    expo_sum = np.sum(np.exp(X))
    return expo/expo_sum

def dense_layer(x, w, b):
    temp = np.matmul(x,w)
    o = temp + b
    return relu(o)

def output_layer(x, w, b):
    temp = np.matmul(x,w)
    o = temp + b
    return softmax(o)

In [18]:
x = np.ones((1,W01), dtype='f4')
correct = 0
for k in range(X_test.shape[0]):
    for i in range(W01):
        x[0][i] = (X_test.values[k][i])
        x[0][i] = np.float32(x[0][i])
#     print(type(x[0][3]))
    out1 = dense_layer(x, w1, b1)
    out2 = dense_layer(out1, w2, b2)
    out3 = dense_layer(out2, w3, b3)
    out4 = dense_layer(out3, w4, b4)
    pred = output_layer(out4, w5, b5)
    
    
    print(np.argmax(pred), y_test[k])
    print(pred)
    if (np.argmax(pred) == y_test[k]):
        correct += 1

print("TOTAL ACCURACY: ", correct/X_test.shape[0])


1 1
[[5.1711395e-04 9.9937093e-01 1.1208193e-04]]
1 1
[[0.20834482 0.7903429  0.00131227]]
0 0
[[0.9959529  0.00115162 0.00289547]]
0 0
[[0.99251735 0.0029453  0.00453742]]
1 1
[[1.9162175e-03 9.9805129e-01 3.2472213e-05]]
2 2
[[6.2344994e-02 2.5544927e-05 9.3762946e-01]]
2 2
[[1.1575703e-04 2.4840492e-03 9.9740022e-01]]
1 1
[[7.2567107e-04 9.9914336e-01 1.3098565e-04]]
0 0
[[9.9961030e-01 3.1860612e-04 7.1120157e-05]]
0 0
[[9.9984068e-01 1.5898829e-04 3.5383485e-07]]
0 0
[[0.9835587  0.00374488 0.01269639]]
0 0
[[9.9001193e-01 9.9659087e-03 2.2181799e-05]]
0 0
[[9.9999779e-01 1.0313656e-08 2.2019733e-06]]
1 1
[[4.0142043e-04 9.9958497e-01 1.3632587e-05]]
1 1
[[8.638121e-03 9.913557e-01 6.187180e-06]]
1 1
[[2.6231873e-04 9.9971712e-01 2.0600664e-05]]
0 0
[[9.7560638e-01 1.0031878e-05 2.4383599e-02]]
1 1
[[5.768910e-05 9.997723e-01 1.700086e-04]]
0 0
[[9.9978727e-01 1.1170042e-05 2.0148525e-04]]
0 0
[[0.91164327 0.0119833  0.07637344]]
2 2
[[0.00483109 0.16059637 0.83457255]]
0 0
[[0.91

2 1
[[0.22214846 0.29188848 0.48596308]]
2 2
[[1.2730129e-02 6.8536028e-04 9.8658454e-01]]
0 1
[[0.8028496  0.17907292 0.01807747]]
1 1
[[7.9222827e-04 9.9785143e-01 1.3563618e-03]]
1 1
[[6.2373478e-02 9.3680847e-01 8.1805448e-04]]
2 2
[[0.02074739 0.02413092 0.95512176]]
2 2
[[3.8865597e-05 2.9252982e-03 9.9703586e-01]]
2 2
[[1.8240105e-05 1.2701498e-04 9.9985474e-01]]
1 1
[[2.4485667e-03 9.9748421e-01 6.7242276e-05]]
2 2
[[8.9222519e-04 4.8730844e-06 9.9910295e-01]]
0 0
[[9.620677e-01 3.788939e-02 4.296099e-05]]
0 0
[[0.8528083  0.14486577 0.00232596]]
1 1
[[2.7298250e-03 9.9725717e-01 1.2970773e-05]]
1 1
[[0.02023051 0.97284096 0.00692856]]
2 2
[[0.00225978 0.00243266 0.99530756]]
1 1
[[0.00506088 0.99241513 0.00252404]]
2 2
[[0.00656687 0.01939607 0.9740371 ]]
1 1
[[0.00866873 0.99018633 0.00114497]]
1 1
[[1.3022361e-02 9.8697454e-01 3.1034483e-06]]
0 0
[[9.9987972e-01 7.2124767e-06 1.1309139e-04]]
1 1
[[1.8743720e-02 9.8109084e-01 1.6548811e-04]]
0 1
[[9.93548751e-01 6.34338101e-0